# This secret should contain the contents of your .ovpn profile
# downloaded from the OpenVPN web interface.
apiVersion: v1
stringData:
  connector.conf: |
    replace me with .ovpn contents
kind: Secret
metadata:
  creationTimestamp: null
  name: openvpn-connector-config
